174 set realistic parameters for paper example
BAMresearch/LebeDigital pull request #177
Opened 2023-06-09 14:25 UTC by eriktamsen

Updated the input parameter for the optimization workflow to be as close to the final values as can be estimated right now.
Some small additions to the snakemake workflow.

2023-06-15 13:04 UTC, joergfunger requested changes
I think I somehow reviewed the wrong merge request, but the comments are pretty much the same? Should I redo these comments, or could you work on the other merge request?

2023-06-15 13:04 UTC, joergfunger commented on lebedigital/demonstrator_scripts/computation_sc_volume_fraction.py
> +        mass_sub = 1 * ureg("kg") / (1 + (1 - input_dic["sc_mass_fraction"]) / input_dic["sc_mass_fraction"])
not sure I can follow this formula, is that the mass of cement substitute per m³ of concrete?

2023-06-15 13:04 UTC, joergfunger commented on lebedigital/demonstrator_scripts/computation_sc_volume_fraction.py
> +        mass_cem = 1 * ureg("kg") - mass_sub
m_c = 1kg-m_s?? see my comments in the other review

2023-06-15 16:03 UTC, eriktamsen commented
@joergfunger: First of all, thanks for going through it. I will check your questions one by one. Quite possible that with all the additional changes, some mistakes have been introduced. I will try to make it work with the comments in the other PR. Should I answer them in the other branch and add changes to this one? Or should we just work with the other PR. Basically this branch is already merged in the other one.

2023-06-16 04:10 UTC, joergfunger commented
If everything is in the other branch already, (and that was that one that I accidently reviewed), I would suggest using the other and deleting this one.

2023-06-16 06:37 UTC, eriktamsen commented
Closing this PR, as already merged in newer PR #181

2023-06-16 06:37 UTC, closed without merging