adding extraction script for mixture metadata
BAMresearch/LebeDigital pull request #39
Opened 2022-07-21 07:41 UTC by alFrie

I added the metadata-extraction script for the mixture set to the new structure.

2022-07-21 08:24 UTC, joergfunger requested changes
The file looks good to me, no comments. Though I would actually like to add only new functions that are actually tested. I guess you have already done that when developing the code. Maybe you could send that to @soudehMasoudian so that she can write the test in that branch here as well and we are only merging this into main once it is actually tested.

2022-07-21 15:21 UTC, joergfunger commented
Yes, just change the excel sheets. This is not the focus of the project. And then send your tests to @soudehMasoudian such that we could actually integrate the tests directly before merging into main.

2022-09-21 13:08 UTC, joergfunger approved these changes
Thanks, almost ready to merge. IMO, there is only one thing to change related to printing the progress. Then (and that is only a remark), we will have to adapt the procedure to our mix in the demonstrator, because the cement content is there actually decomposed into two different components (cemI and cemII) that we would have to store separately, but lets see how this is represented in the ontology and then we could change that afterwards. This is then another issue to be solved later.

2022-09-21 13:08 UTC, joergfunger commented on lebedigital/raw_data_processing/metadata_extraction/mixture_metadata_extraction.py
> +    print("Sheets containing mixture metadata in this file: " + str(listofkeys))
I think we should add a logger (e.g. loguru as used [here](https://github.com/BAMresearch/probeye/blob/6272085e8c69131b43b6a90c81f502636d3aa59d/probeye/definition/forward_model.py#L5) not to clutter the output with debugging information. An simple alternative would be to define a debug=True variable at the top and put that print statements into an if statement.

2022-09-21 13:08 UTC, joergfunger commented on lebedigital/raw_data_processing/metadata_extraction/mixture_metadata_extraction.py
> +        metadata["watercementratio"] = exceltodf.iloc[idx,2] #7
what are these numbers #7 as comments?

2022-09-21 14:05 UTC, eriktamsen requested changes
Thank you for the changes in the script. This look good.
Please move the script to a different folder as suggested in #55 and already implemented in main.

2022-09-21 14:50 UTC, joergfunger commented on lebedigital/raw_data_processing/metadata_extraction/mixture_metadata_extraction.py
> +        metadata["watercementratio"] = exceltodf.iloc[idx,2] #7
I would recompute it.

2022-09-22 06:07 UTC, joergfunger commented on lebedigital/raw_data_processing/metadata_extraction/mixture_metadata_extraction.py
> +        metadata["watercementratio"] = exceltodf.iloc[idx,2] #7
Just use the ratio between mass of water and mass of cement both given in the excel sheet separately. That should evaluate to a numeric value somewhere between 0.2 and 0.7 and should agree with the entry in this cell (without the additional sometimes weird comments that we currently do not use anyway).

2022-09-22 13:08 UTC, eriktamsen commented on lebedigital/raw_data_processing/metadata_extraction/mixture_metadata_extraction.py
> +        string = nan
I dont have an elegant solution. I would define a function e.g.:
def my_float(string):
   if string:
      string = float(string)
   
   return string

2022-09-22 13:43 UTC, eriktamsen commented on lebedigital/raw_data_processing/metadata_extraction/mixture_metadata_extraction.py
> +        string = nan
I guess you are right. I did not know that "nan" is a possible float value. Should be good enough.
Ignore my comment ;).

2022-09-22 15:20 UTC, joergfunger commented on lebedigital/raw_data_processing/metadata_extraction/mixture_metadata_extraction.py
> +        string = nan
Instead of adding a NaN or None, could we just don't include that key-value pair in the file? Then there is only valid data in the yaml-file.

2022-09-23 08:30 UTC, joergfunger commented
Can you join the two pull request (unit tests + metadata extraction).

2022-09-27 11:07 UTC, joergfunger commented
> > Please move the script to a different folder as suggested in #55 and already implemented in main.
> 
> I can't do that while still working on my branch, right? This new folder didn't exist in the main branch when I created mine. Is there a way to change this, should I create a new branch or do I have to move it when it is merged with main? @eriktamsen

You can merge the main branch into your branch, perform all the changes and then merge back. After having merged main into your feature branch, the directory structure should be updated.

2022-10-11 15:45 UTC, joergfunger approved these changes
Just very minor changes required, in particular moving the file since the mixture is general and not only for Youngs-modulus tests. Thanks a lot, looks very nice.

2022-10-11 15:45 UTC, joergfunger commented on lebedigital/raw_data_processing/youngs_modulus_data/mixture_metadata_extraction.py
> +def isNaN(num):
why not use standard functions such as [this](https://numpy.org/doc/stable/reference/generated/numpy.isnan.html)

2022-10-11 15:45 UTC, joergfunger commented on lebedigital/raw_data_processing/youngs_modulus_data/mixture_metadata_extraction.py
> +# Script for metadata-extraction:
We should move the file to mixture (instead of Youngs modulus), because the mixture is not related to a specific (Youngs) modulus test.

2022-10-12 13:08 UTC, joergfunger commented on lebedigital/raw_data_processing/youngs_modulus_data/mixture_metadata_extraction.py
> +# Script for metadata-extraction:
no, that has to be created

2022-10-15 12:39 UTC, eriktamsen approved these changes
Look great, thanks.

2022-10-17 04:12 UTC, merged